import React, { Component } from 'react';
import { ReactMic } from 'react-mic';
//import Header from "../../static/img/1.png";
import Select from 'react-select';
import {Row, Col, Button} from "react-materialize";
export const scaryAnimals = [
  { label: "/Adult", value: 1 },
  { label: "/Arts & Entertainment", value: 2 },
  { label: "/Arts & Entertainment/Celebrities & Entertainment News", value: 3 },
  { label: "/Arts & Entertainment/Comics & Animation", value: 4 },
  { label: "/Arts & Entertainment/Comics & Animation/Anime & Manga", value: 5 },
  { label: "/Arts & Entertainment/Comics & Animation/Cartoons", value: 6 },
  { label: "/Arts & Entertainment/Comics & Animation/Comics", value: 7 },
  { label: "/Arts & Entertainment/Entertainment Industry", value: 8 },
  { label: "/Arts & Entertainment/Entertainment Industry/Film & TV Industry", value: 9 },
  { label: "/Arts & Entertainment/Entertainment Industry/Recording Industry", value: 10 },
  { label: "/Arts & Entertainment/Events & Listings", value: 11 },
  { label: "/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife", value: 12 },
  { label: "/Arts & Entertainment/Events & Listings/Concerts & Music Festivals", value: 13 },
  { label: "/Arts & Entertainment/Events & Listings/Expos & Conventions", value: 14 },
  { label: "/Arts & Entertainment/Events & Listings/Film Festivals", value: 15 },
  { label: "/Arts & Entertainment/Events & Listings/Movie Listings & Theater Showtimes", value: 16 },
  { label: "/Arts & Entertainment/Fun & Trivia", value: 17 },
  { label: "/Arts & Entertainment/Fun & Trivia/Flash-Based Entertainment", value: 18 },
  { label: "/Arts & Entertainment/Fun & Trivia/Fun Tests & Silly Surveys", value: 19 },
  { label: "/Arts & Entertainment/Humor", value: 20 },
  { label: "/Arts & Entertainment/Humor/Funny Pictures & Videos", value: 21 },
  { label: "/Arts & Entertainment/Humor/Political Humor", value: 22 },
  { label: "/Arts & Entertainment/Movies", value: 23 },
  { label: "/Arts & Entertainment/Music & Audio", value: 24 },
  { label: "/Arts & Entertainment/Music & Audio/CD & Audio Shopping", value: 25 },
  { label: "/Arts & Entertainment/Music & Audio/Classical Music", value: 26 },
  { label: "/Arts & Entertainment/Music & Audio/Country Music", value: 27 },
  { label: "/Arts & Entertainment/Music & Audio/Dance & Electronic Music", value: 28 },
  { label: "/Arts & Entertainment/Music & Audio/Experimental & Industrial Music", value: 29 },
  { label: "/Arts & Entertainment/Music & Audio/Jazz & Blues", value: 30 },
  { label: "/Arts & Entertainment/Music & Audio/Music Education & Instruction", value: 31 },
  { label: "/Arts & Entertainment/Music & Audio/Music Equipment & Technology", value: 32 },
  { label: "/Arts & Entertainment/Music & Audio/Music Reference", value: 33 },
  { label: "/Arts & Entertainment/Music & Audio/Music Streams & Downloads", value: 34 },
  { label: "/Arts & Entertainment/Music & Audio/Music Videos", value: 35 },
  { label: "/Arts & Entertainment/Music & Audio/Pop Music", value: 36 },
  { label: "/Arts & Entertainment/Music & Audio/Radio", value: 37 },
  { label: "/Arts & Entertainment/Music & Audio/Religious Music", value: 38 },
  { label: "/Arts & Entertainment/Music & Audio/Rock Music", value: 39 },
  { label: "/Arts & Entertainment/Music & Audio/Soundtracks", value: 40 },
  { label: "/Arts & Entertainment/Music & Audio/Urban & Hip-Hop", value: 41 },
  { label: "/Arts & Entertainment/Music & Audio/World Music", value: 42 },
  { label: "/Arts & Entertainment/Offbeat", value: 43 },
  { label: "/Arts & Entertainment/Offbeat/Occult & Paranormal", value: 44 },
  { label: "/Arts & Entertainment/Online Media", value: 45 },
  { label: "/Arts & Entertainment/Online Media/Online Image Galleries", value: 46 },
  { label: "/Arts & Entertainment/Performing Arts", value: 47 },
  { label: "/Arts & Entertainment/Performing Arts/Acting & Theater", value: 48 },
  { label: "/Arts & Entertainment/Performing Arts/Circus", value: 49 },
  { label: "/Arts & Entertainment/Performing Arts/Dance", value: 50 },
  { label: "/Arts & Entertainment/Performing Arts/Magic", value: 51 },
  { label: "/Arts & Entertainment/Performing Arts/Opera", value: 52 },
  { label: "/Arts & Entertainment/TV & Video", value: 53 },
  { label: "/Arts & Entertainment/TV & Video/Online Video", value: 54 },
  { label: "/Arts & Entertainment/TV & Video/TV Commercials", value: 55 },
  { label: "/Arts & Entertainment/TV & Video/TV Shows & Programs", value: 56 },
  { label: "/Arts & Entertainment/Visual Art & Design", value: 57 },
  { label: "/Arts & Entertainment/Visual Art & Design/Architecture", value: 58 },
  { label: "/Arts & Entertainment/Visual Art & Design/Art Museums & Galleries", value: 59 },
  { label: "/Arts & Entertainment/Visual Art & Design/Design", value: 60 },
  { label: "/Arts & Entertainment/Visual Art & Design/Painting", value: 61 },
  { label: "/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts", value: 62 },
  { label: "/Autos & Vehicles", value: 63 },
  { label: "/Autos & Vehicles/Bicycles & Accessories", value: 64 },
  { label: "/Autos & Vehicles/Bicycles & Accessories/BMX Bikes", value: 65 },
  { label: "/Autos & Vehicles/Bicycles & Accessories/Bike Parts & Repair", value: 66 },
  { label: "/Autos & Vehicles/Boats & Watercraft", value: 67 },
  { label: "/Autos & Vehicles/Campers & RVs", value: 68 },
  { label: "/Autos & Vehicles/Classic Vehicles", value: 69 },
  { label: "/Autos & Vehicles/Commercial Vehicles/Cargo Trucks & Trailers", value: 70 },
  { label: "/Autos & Vehicles/Motor Vehicles (By Type)", value: 71 },
  { label: "/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles", value: 72 },
  { label: "/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles", value: 73 },
  { label: "/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles", value: 74 },
  { label: "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks & SUVs", value: 75 },
  { label: "/Autos & Vehicles/Vehicle Codes & Driving Laws", value: 76 },
  { label: "/Autos & Vehicles/Vehicle Codes & Driving Laws/Vehicle Licensing & Registration", value: 77 },
  { label: "/Autos & Vehicles/Vehicle Parts & Services", value: 78 },
  { label: "/Autos & Vehicles/Vehicle Parts & Services/Gas Prices & Vehicle Fueling", value: 79 },
  { label: "/Autos & Vehicles/Vehicle Parts & Services/Vehicle Parts & Accessories", value: 80 },
  { label: "/Autos & Vehicles/Vehicle Parts & Services/Vehicle Repair & Maintenance", value: 81 },
  { label: "/Autos & Vehicles/Vehicle Shopping", value: 82 },
  { label: "/Autos & Vehicles/Vehicle Shopping/Used Vehicles", value: 83 },
  { label: "/Autos & Vehicles/Vehicle Shows", value: 84 },
  { label: "/Beauty & Fitness", value: 85 },
  { label: "/Beauty & Fitness/Beauty Pageants", value: 86 },
  { label: "/Beauty & Fitness/Body Art", value: 87 },
  { label: "/Beauty & Fitness/Cosmetic Procedures", value: 88 },
  { label: "/Beauty & Fitness/Cosmetic Procedures/Cosmetic Surgery", value: 89 },
  { label: "/Beauty & Fitness/Cosmetology & Beauty Professionals", value: 90 },
  { label: "/Beauty & Fitness/Face & Body Care", value: 91 },
  { label: "/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries", value: 92 },
  { label: "/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics", value: 93 },
  { label: "/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances", value: 94 },
  { label: "/Beauty & Fitness/Face & Body Care/Skin & Nail Care", value: 95 },
  { label: "/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal", value: 96 },
  { label: "/Beauty & Fitness/Fashion & Style", value: 97 },
  { label: "/Beauty & Fitness/Fashion & Style/Fashion Designers & Collections", value: 98 },
  { label: "/Beauty & Fitness/Fitness", value: 99 },
  { label: "/Beauty & Fitness/Hair Care", value: 100 },
  { label: "/Beauty & Fitness/Hair Care/Hair Loss", value: 101 },
  { label: "/Beauty & Fitness/Spas & Beauty Services", value: 102 },
  { label: "/Beauty & Fitness/Spas & Beauty Services/Massage Therapy", value: 103 },
  { label: "/Beauty & Fitness/Weight Loss", value: 104 },
  { label: "/Books & Literature", value: 105 },
  { label: "/Books & Literature/Children's Literature", value: 106 },
  { label: "/Books & Literature/E-Books", value: 107 },
  { label: "/Books & Literature/Fan Fiction", value: 108 },
  { label: "/Books & Literature/Literary Classics", value: 109 },
  { label: "/Books & Literature/Poetry", value: 110 },
  { label: "/Books & Literature/Writers Resources", value: 111 },
  { label: "/Business & Industrial", value: 112 },
  { label: "/Business & Industrial/Advertising & Marketing/Public Relations", value: 113 },
  { label: "/Business & Industrial/Aerospace & Defense/Space Technology", value: 114 },
  { label: "/Business & Industrial/Agriculture & Forestry", value: 115 },
  { label: "/Business & Industrial/Agriculture & Forestry/Agricultural Equipment", value: 116 },
  { label: "/Business & Industrial/Agriculture & Forestry/Forestry", value: 117 },
  { label: "/Business & Industrial/Agriculture & Forestry/Livestock", value: 118 },
  { label: "/Business & Industrial/Automotive Industry", value: 119 },
  { label: "/Business & Industrial/Business Education", value: 120 },
  { label: "/Business & Industrial/Business Finance", value: 121 },
  { label: "/Business & Industrial/Business Finance/Venture Capital", value: 122 },
  { label: "/Business & Industrial/Business Operations", value: 123 },
  { label: "/Business & Industrial/Business Operations/Business Plans & Presentations", value: 124 },
  { label: "/Business & Industrial/Business Operations/Management", value: 125 },
  { label: "/Business & Industrial/Business Services", value: 126 },
  { label: "/Business & Industrial/Business Services/Consulting", value: 127 },
  { label: "/Business & Industrial/Business Services/Corporate Events", value: 128 },
  { label: "/Business & Industrial/Business Services/E-Commerce Services", value: 129 },
  { label: "/Business & Industrial/Business Services/Fire & Security Services", value: 130 },
  { label: "/Business & Industrial/Business Services/Office Services", value: 131 },
  { label: "/Business & Industrial/Business Services/Office Supplies", value: 132 },
  { label: "/Business & Industrial/Business Services/Writing & Editing Services", value: 133 },
  { label: "/Business & Industrial/Chemicals Industry", value: 134 },
  { label: "/Business & Industrial/Chemicals Industry/Cleaning Agents", value: 135 },
  { label: "/Business & Industrial/Chemicals Industry/Plastics & Polymers", value: 136 },
  { label: "/Business & Industrial/Construction & Maintenance", value: 137 },
  { label: "/Business & Industrial/Construction & Maintenance/Building Materials & Supplies", value: 138 },
  { label: "/Business & Industrial/Energy & Utilities", value: 139 },
  { label: "/Business & Industrial/Energy & Utilities/Electricity", value: 140 },
  { label: "/Business & Industrial/Energy & Utilities/Oil & Gas", value: 141 },
  { label: "/Business & Industrial/Energy & Utilities/Renewable & Alternative Energy", value: 142 },
  { label: "/Business & Industrial/Hospitality Industry", value: 143 },
  { label: "/Business & Industrial/Hospitality Industry/Event Planning", value: 144 },
  { label: "/Business & Industrial/Hospitality Industry/Food Service", value: 145 },
  { label: "/Business & Industrial/Industrial Materials & Equipment", value: 146 },
  { label: "/Business & Industrial/Industrial Materials & Equipment/Heavy Machinery", value: 147 },
  { label: "/Business & Industrial/Manufacturing", value: 148 },
  { label: "/Business & Industrial/Metals & Mining", value: 149 },
  { label: "/Business & Industrial/Metals & Mining/Precious Metals", value: 150 },
  { label: "/Business & Industrial/Pharmaceuticals & Biotech", value: 151 },
  { label: "/Business & Industrial/Printing & Publishing", value: 152 },
  { label: "/Business & Industrial/Retail Trade", value: 153 },
  { label: "/Business & Industrial/Retail Trade/Retail Equipment & Technology", value: 154 },
  { label: "/Business & Industrial/Small Business/MLM & Business Opportunities", value: 155 },
  { label: "/Business & Industrial/Textiles & Nonwovens", value: 156 },
  { label: "/Business & Industrial/Transportation & Logistics", value: 157 },
  { label: "/Business & Industrial/Transportation & Logistics/Freight & Trucking", value: 158 },
  { label: "/Business & Industrial/Transportation & Logistics/Mail & Package Delivery", value: 159 },
  { label: "/Business & Industrial/Transportation & Logistics/Maritime Transport", value: 160 },
  { label: "/Business & Industrial/Transportation & Logistics/Moving & Relocation", value: 161 },
  { label: "/Business & Industrial/Transportation & Logistics/Packaging", value: 162 },
  { label: "/Business & Industrial/Transportation & Logistics/Parking", value: 163 },
  { label: "/Business & Industrial/Transportation & Logistics/Rail Transport", value: 164 },
  { label: "/Business & Industrial/Transportation & Logistics/Urban Transport", value: 165 },
  { label: "/Computers & Electronics", value: 166 },
  { label: "/Computers & Electronics/CAD & CAM", value: 167 },
  { label: "/Computers & Electronics/Computer Hardware", value: 168 },
  { label: "/Computers & Electronics/Computer Hardware/Computer Components", value: 169 },
  { label: "/Computers & Electronics/Computer Hardware/Computer Drives & Storage", value: 170 },
  { label: "/Computers & Electronics/Computer Hardware/Computer Peripherals", value: 171 },
  { label: "/Computers & Electronics/Computer Hardware/Desktop Computers", value: 172 },
  { label: "/Computers & Electronics/Computer Hardware/Laptops & Notebooks", value: 173 },
  { label: "/Computers & Electronics/Computer Security", value: 174 },
  { label: "/Computers & Electronics/Computer Security/Hacking & Cracking", value: 175 },
  { label: "/Computers & Electronics/Consumer Electronics", value: 176 },
  { label: "/Computers & Electronics/Consumer Electronics/Audio Equipment", value: 177 },
  { label: "/Computers & Electronics/Consumer Electronics/Camera & Photo Equipment", value: 178 },
  { label: "/Computers & Electronics/Consumer Electronics/Car Electronics", value: 179 },
  { label: "/Computers & Electronics/Consumer Electronics/Drones & RC Aircraft", value: 180 },
  { label: "/Computers & Electronics/Consumer Electronics/GPS & Navigation", value: 181 },
  { label: "/Computers & Electronics/Consumer Electronics/Game Systems & Consoles", value: 182 },
  { label: "/Computers & Electronics/Consumer Electronics/TV & Video Equipment", value: 183 },
  { label: "/Computers & Electronics/Electronics & Electrical", value: 184 },
  { label: "/Computers & Electronics/Electronics & Electrical/Electronic Components", value: 185 },
  { label: "/Computers & Electronics/Electronics & Electrical/Power Supplies", value: 186 },
  { label: "/Computers & Electronics/Enterprise Technology", value: 187 },
  { label: "/Computers & Electronics/Enterprise Technology/Data Management", value: 188 },
  { label: "/Computers & Electronics/Networking", value: 189 },
  { label: "/Computers & Electronics/Networking/Data Formats & Protocols", value: 190 },
  { label: "/Computers & Electronics/Networking/Network Monitoring & Management", value: 191 },
  { label: "/Computers & Electronics/Networking/VPN & Remote Access", value: 192 },
  { label: "/Computers & Electronics/Programming", value: 193 },
  { label: "/Computers & Electronics/Programming/Java (Programming Language)", value: 194 },
  { label: "/Computers & Electronics/Software", value: 195 },
  { label: "/Computers & Electronics/Software/Business & Productivity Software", value: 196 },
  { label: "/Computers & Electronics/Software/Device Drivers", value: 197 },
  { label: "/Computers & Electronics/Software/Internet Software", value: 198 },
  { label: "/Computers & Electronics/Software/Multimedia Software", value: 199 },
  { label: "/Computers & Electronics/Software/Operating Systems", value: 200 },
  { label: "/Computers & Electronics/Software/Software Utilities", value: 201 },
  { label: "/Finance", value: 202 },
  { label: "/Finance/Accounting & Auditing", value: 203 },
  { label: "/Finance/Accounting & Auditing/Billing & Invoicing", value: 204 },
  { label: "/Finance/Accounting & Auditing/Tax Preparation & Planning", value: 205 },
  { label: "/Finance/Banking", value: 206 },
  { label: "/Finance/Credit & Lending", value: 207 },
  { label: "/Finance/Credit & Lending/Credit Cards", value: 208 },
  { label: "/Finance/Credit & Lending/Credit Reporting & Monitoring", value: 209 },
  { label: "/Finance/Credit & Lending/Loans", value: 210 },
  { label: "/Finance/Financial Planning & Management", value: 211 },
  { label: "/Finance/Financial Planning & Management/Retirement & Pension", value: 212 },
  { label: "/Finance/Grants, Scholarships & Financial Aid", value: 213 },
  { label: "/Finance/Grants, Scholarships & Financial Aid/Study Grants & Scholarships", value: 214 },
  { label: "/Finance/Insurance", value: 215 },
  { label: "/Finance/Insurance/Health Insurance", value: 216 },
  { label: "/Finance/Investing", value: 217 },
  { label: "/Finance/Investing/Commodities & Futures Trading", value: 218 },
  { label: "/Finance/Investing/Currencies & Foreign Exchange", value: 219 },
  { label: "/Finance/Investing/Stocks & Bonds", value: 220 },
  { label: "/Food & Drink", value: 221 },
  { label: "/Food & Drink/Beverages", value: 222 },
  { label: "/Food & Drink/Beverages/Alcoholic Beverages", value: 223 },
  { label: "/Food & Drink/Beverages/Coffee & Tea", value: 224 },
  { label: "/Food & Drink/Beverages/Juice", value: 225 },
  { label: "/Food & Drink/Beverages/Soft Drinks", value: 226 },
  { label: "/Food & Drink/Cooking & Recipes", value: 227 },
  { label: "/Food & Drink/Cooking & Recipes/BBQ & Grilling", value: 228 },
  { label: "/Food & Drink/Cooking & Recipes/Desserts", value: 229 },
  { label: "/Food & Drink/Cooking & Recipes/Soups & Stews", value: 230 },
  { label: "/Food & Drink/Food", value: 231 },
  { label: "/Food & Drink/Food & Grocery Retailers", value: 232 },
  { label: "/Food & Drink/Food/Baked Goods", value: 233 },
  { label: "/Food & Drink/Food/Breakfast Foods", value: 234 },
  { label: "/Food & Drink/Food/Candy & Sweets", value: 235 },
  { label: "/Food & Drink/Food/Grains & Pasta", value: 236 },
  { label: "/Food & Drink/Food/Meat & Seafood", value: 237 },
  { label: "/Food & Drink/Food/Snack Foods", value: 238 },
  { label: "/Food & Drink/Restaurants", value: 239 },
  { label: "/Food & Drink/Restaurants/Fast Food", value: 240 },
  { label: "/Food & Drink/Restaurants/Pizzerias", value: 241 },
  { label: "/Food & Drink/Restaurants/Restaurant Reviews & Reservations", value: 242 },
  { label: "/Games", value: 243 },
  { label: "/Games/Arcade & Coin-Op Games", value: 244 },
  { label: "/Games/Board Games", value: 245 },
  { label: "/Games/Board Games/Chess & Abstract Strategy Games", value: 246 },
  { label: "/Games/Board Games/Miniatures & Wargaming", value: 247 },
  { label: "/Games/Card Games", value: 248 },
  { label: "/Games/Card Games/Collectible Card Games", value: 249 },
  { label: "/Games/Card Games/Poker & Casino Games", value: 250 },
  { label: "/Games/Computer & Video Games", value: 251 },
  { label: "/Games/Computer & Video Games/Casual Games", value: 252 },
  { label: "/Games/Computer & Video Games/Driving & Racing Games", value: 253 },
  { label: "/Games/Computer & Video Games/Fighting Games", value: 254 },
  { label: "/Games/Computer & Video Games/Music & Dance Games", value: 255 },
  { label: "/Games/Computer & Video Games/Sandbox Games", value: 256 },
  { label: "/Games/Computer & Video Games/Shooter Games", value: 257 },
  { label: "/Games/Computer & Video Games/Simulation Games", value: 258 },
  { label: "/Games/Computer & Video Games/Sports Games", value: 259 },
  { label: "/Games/Computer & Video Games/Strategy Games", value: 260 },
  { label: "/Games/Computer & Video Games/Video Game Emulation", value: 261 },
  { label: "/Games/Family-Oriented Games & Activities", value: 262 },
  { label: "/Games/Family-Oriented Games & Activities/Drawing & Coloring", value: 263 },
  { label: "/Games/Family-Oriented Games & Activities/Dress-Up & Fashion Games", value: 264 },
  { label: "/Games/Gambling", value: 265 },
  { label: "/Games/Gambling/Lottery", value: 266 },
  { label: "/Games/Online Games/Massively Multiplayer Games", value: 267 },
  { label: "/Games/Puzzles & Brainteasers", value: 268 },
  { label: "/Games/Roleplaying Games", value: 269 },
  { label: "/Games/Table Games", value: 270 },
  { label: "/Games/Table Games/Billiards", value: 271 },
  { label: "/Games/Word Games", value: 272 },
  { label: "/Health", value: 273 },
  { label: "/Health/Aging & Geriatrics", value: 274 },
  { label: "/Health/Health Conditions", value: 275 },
  { label: "/Health/Health Conditions/AIDS & HIV", value: 276 },
  { label: "/Health/Health Conditions/Allergies", value: 277 },
  { label: "/Health/Health Conditions/Arthritis", value: 278 },
  { label: "/Health/Health Conditions/Cancer", value: 279 },
  { label: "/Health/Health Conditions/Diabetes", value: 280 },
  { label: "/Health/Health Conditions/Ear Nose & Throat", value: 281 },
  { label: "/Health/Health Conditions/Eating Disorders", value: 282 },
  { label: "/Health/Health Conditions/Endocrine Conditions", value: 283 },
  { label: "/Health/Health Conditions/Genetic Disorders", value: 284 },
  { label: "/Health/Health Conditions/Heart & Hypertension", value: 285 },
  { label: "/Health/Health Conditions/Infectious Diseases", value: 286 },
  { label: "/Health/Health Conditions/Neurological Conditions", value: 287 },
  { label: "/Health/Health Conditions/Obesity", value: 288 },
  { label: "/Health/Health Conditions/Pain Management", value: 289 },
  { label: "/Health/Health Conditions/Respiratory Conditions", value: 290 },
  { label: "/Health/Health Conditions/Skin Conditions", value: 291 },
  { label: "/Health/Health Conditions/Sleep Disorders", value: 292 },
  { label: "/Health/Health Education & Medical Training", value: 293 },
  { label: "/Health/Health Foundations & Medical Research", value: 294 },
  { label: "/Health/Medical Devices & Equipment", value: 295 },
  { label: "/Health/Medical Facilities & Services", value: 296 },
  { label: "/Health/Medical Facilities & Services/Doctors' Offices", value: 297 },
  { label: "/Health/Medical Facilities & Services/Hospitals & Treatment Centers", value: 298 },
  { label: "/Health/Medical Facilities & Services/Medical Procedures", value: 299 },
  { label: "/Health/Medical Facilities & Services/Physical Therapy", value: 300 },
  { label: "/Health/Men's Health", value: 301 },
  { label: "/Health/Mental Health", value: 302 },
  { label: "/Health/Mental Health/Anxiety & Stress", value: 303 },
  { label: "/Health/Mental Health/Depression", value: 304 },
  { label: "/Health/Nursing", value: 305 },
  { label: "/Health/Nursing/Assisted Living & Long Term Care", value: 306 },
  { label: "/Health/Nutrition", value: 307 },
  { label: "/Health/Nutrition/Special & Restricted Diets", value: 308 },
  { label: "/Health/Nutrition/Vitamins & Supplements", value: 309 },
  { label: "/Health/Oral & Dental Care", value: 310 },
  { label: "/Health/Pharmacy", value: 311 },
  { label: "/Health/Pharmacy/Drugs & Medications", value: 312 },
  { label: "/Health/Public Health", value: 313 },
  { label: "/Health/Public Health/Occupational Health & Safety", value: 314 },
  { label: "/Health/Reproductive Health", value: 315 },
  { label: "/Health/Substance Abuse", value: 316 },
  { label: "/Health/Substance Abuse/Drug & Alcohol Testing", value: 317 },
  { label: "/Health/Substance Abuse/Drug & Alcohol Treatment", value: 318 },
  { label: "/Health/Substance Abuse/Smoking & Smoking Cessation", value: 319 },
  { label: "/Health/Substance Abuse/Steroids & Performance-Enhancing Drugs", value: 320 },
  { label: "/Health/Vision Care", value: 321 },
  { label: "/Health/Vision Care/Eyeglasses & Contacts", value: 322 },
  { label: "/Health/Women's Health", value: 323 },
  { label: "/Hobbies & Leisure", value: 324 },
  { label: "/Hobbies & Leisure/Clubs & Organizations", value: 325 },
  { label: "/Hobbies & Leisure/Clubs & Organizations/Youth Organizations & Resources", value: 326 },
  { label: "/Hobbies & Leisure/Crafts", value: 327 },
  { label: "/Hobbies & Leisure/Crafts/Fiber & Textile Arts", value: 328 },
  { label: "/Hobbies & Leisure/Merit Prizes & Contests", value: 329 },
  { label: "/Hobbies & Leisure/Outdoors", value: 330 },
  { label: "/Hobbies & Leisure/Outdoors/Fishing", value: 331 },
  { label: "/Hobbies & Leisure/Outdoors/Hiking & Camping", value: 332 },
  { label: "/Hobbies & Leisure/Paintball", value: 333 },
  { label: "/Hobbies & Leisure/Radio Control & Modeling", value: 334 },
  { label: "/Hobbies & Leisure/Radio Control & Modeling/Model Trains & Railroads", value: 335 },
  { label: "/Hobbies & Leisure/Special Occasions", value: 336 },
  { label: "/Hobbies & Leisure/Special Occasions/Holidays & Seasonal Events", value: 337 },
  { label: "/Hobbies & Leisure/Special Occasions/Weddings", value: 338 },
  { label: "/Hobbies & Leisure/Water Activities", value: 339 },
  { label: "/Hobbies & Leisure/Water Activities/Boating", value: 340 },
  { label: "/Hobbies & Leisure/Water Activities/Surf & Swim", value: 341 },
  { label: "/Home & Garden", value: 342 },
  { label: "/Home & Garden/Bed & Bath", value: 343 },
  { label: "/Home & Garden/Bed & Bath/Bathroom", value: 344 },
  { label: "/Home & Garden/Domestic Services", value: 345 },
  { label: "/Home & Garden/Domestic Services/Cleaning Services", value: 346 },
  { label: "/Home & Garden/Gardening & Landscaping", value: 347 },
  { label: "/Home & Garden/HVAC & Climate Control", value: 348 },
  { label: "/Home & Garden/HVAC & Climate Control/Fireplaces & Stoves", value: 349 },
  { label: "/Home & Garden/Home & Interior Decor", value: 350 },
  { label: "/Home & Garden/Home Appliances", value: 351 },
  { label: "/Home & Garden/Home Furnishings", value: 352 },
  { label: "/Home & Garden/Home Furnishings/Curtains & Window Treatments", value: 353 },
  { label: "/Home & Garden/Home Furnishings/Kitchen & Dining Furniture", value: 354 },
  { label: "/Home & Garden/Home Furnishings/Lamps & Lighting", value: 355 },
  { label: "/Home & Garden/Home Furnishings/Living Room Furniture", value: 356 },
  { label: "/Home & Garden/Home Furnishings/Rugs & Carpets", value: 357 },
  { label: "/Home & Garden/Home Improvement", value: 358 },
  { label: "/Home & Garden/Home Improvement/Construction & Power Tools", value: 359 },
  { label: "/Home & Garden/Home Improvement/Doors & Windows", value: 360 },
  { label: "/Home & Garden/Home Improvement/Flooring", value: 361 },
  { label: "/Home & Garden/Home Improvement/House Painting & Finishing", value: 362 },
  { label: "/Home & Garden/Home Improvement/Plumbing", value: 363 },
  { label: "/Home & Garden/Home Safety & Security", value: 364 },
  { label: "/Home & Garden/Home Storage & Shelving", value: 365 },
  { label: "/Home & Garden/Home Swimming Pools, Saunas & Spas", value: 366 },
  { label: "/Home & Garden/Kitchen & Dining", value: 367 },
  { label: "/Home & Garden/Kitchen & Dining/Cookware & Diningware", value: 368 },
  { label: "/Home & Garden/Kitchen & Dining/Major Kitchen Appliances", value: 369 },
  { label: "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances", value: 370 },
  { label: "/Home & Garden/Laundry", value: 371 },
  { label: "/Home & Garden/Laundry/Washers & Dryers", value: 372 },
  { label: "/Home & Garden/Nursery & Playroom", value: 373 },
  { label: "/Home & Garden/Pest Control", value: 374 },
  { label: "/Home & Garden/Yard & Patio", value: 375 },
  { label: "/Home & Garden/Yard & Patio/Lawn Mowers", value: 376 },
  { label: "/Internet & Telecom", value: 377 },
  { label: "/Internet & Telecom/Communications Equipment", value: 378 },
  { label: "/Internet & Telecom/Communications Equipment/Radio Equipment", value: 379 },
  { label: "/Internet & Telecom/Email & Messaging", value: 380 },
  { label: "/Internet & Telecom/Email & Messaging/Text & Instant Messaging", value: 381 },
  { label: "/Internet & Telecom/Email & Messaging/Voice & Video Chat", value: 382 },
  { label: "/Internet & Telecom/Mobile & Wireless", value: 383 },
  { label: "/Internet & Telecom/Mobile & Wireless/Mobile & Wireless Accessories", value: 384 },
  { label: "/Internet & Telecom/Mobile & Wireless/Mobile Apps & Add-Ons", value: 385 },
  { label: "/Internet & Telecom/Mobile & Wireless/Mobile Phones", value: 386 },
  { label: "/Internet & Telecom/Service Providers", value: 387 },
  { label: "/Internet & Telecom/Service Providers/Cable & Satellite Providers", value: 388 },
  { label: "/Internet & Telecom/Web Services", value: 389 },
  { label: "/Internet & Telecom/Web Services/Affiliate Programs", value: 390 },
  { label: "/Internet & Telecom/Web Services/Web Design & Development", value: 391 },
  { label: "/Jobs & Education", value: 392 },
  { label: "/Jobs & Education/Education", value: 393 },
  { label: "/Jobs & Education/Education/Colleges & Universities", value: 394 },
  { label: "/Jobs & Education/Education/Distance Learning", value: 395 },
  { label: "/Jobs & Education/Education/Homeschooling", value: 396 },
  { label: "/Jobs & Education/Education/Primary & Secondary Schooling (K-12", value: 397 },
  { label: "/Jobs & Education/Education/Standardized & Admissions Tests", value: 398 },
  { label: "/Jobs & Education/Education/Teaching & Classroom Resources", value: 399 },
  { label: "/Jobs & Education/Education/Training & Certification", value: 400 },
  { label: "/Jobs & Education/Education/Vocational & Continuing Education", value: 401 },
  { label: "/Jobs & Education/Jobs", value: 402 },
  { label: "/Jobs & Education/Jobs/Career Resources & Planning", value: 403 },
  { label: "/Jobs & Education/Jobs/Job Listings", value: 404 },
  { label: "/Jobs & Education/Jobs/Resumes & Portfolios", value: 405 },
  { label: "/Law & Government", value: 406 },
  { label: "/Law & Government/Government", value: 407 },
  { label: "/Law & Government/Government/Courts & Judiciary", value: 408 },
  { label: "/Law & Government/Government/Visa & Immigration", value: 409 },
  { label: "/Law & Government/Legal", value: 410 },
  { label: "/Law & Government/Legal/Bankruptcy", value: 411 },
  { label: "/Law & Government/Legal/Legal Education", value: 412 },
  { label: "/Law & Government/Legal/Legal Services", value: 413 },
  { label: "/Law & Government/Military", value: 414 },
  { label: "/Law & Government/Public Safety", value: 415 },
  { label: "/Law & Government/Public Safety/Crime & Justice", value: 416 },
  { label: "/Law & Government/Public Safety/Emergency Services", value: 417 },
  { label: "/Law & Government/Public Safety/Law Enforcement", value: 418 },
  { label: "/Law & Government/Public Safety/Security Products & Services", value: 419 },
  { label: "/Law & Government/Social Services", value: 420 },
  { label: "/News", value: 421 },
  { label: "/News/Business News", value: 422 },
  { label: "/News/Business News/Company News", value: 423 },
  { label: "/News/Business News/Financial Markets News", value: 424 },
  { label: "/News/Gossip & Tabloid News/Scandals & Investigations", value: 425 },
  { label: "/News/Health News", value: 426 },
  { label: "/News/Politics", value: 427 },
  { label: "/News/Sports News", value: 428 },
  { label: "/News/Weather", value: 429 },
  { label: "/Online Communities", value: 430 },
  { label: "/Online Communities/Blogging Resources & Services", value: 431 },
  { label: "/Online Communities/Dating & Personals", value: 432 },
  { label: "/Online Communities/Dating & Personals/Matrimonial Services", value: 433 },
  { label: "/Online Communities/Dating & Personals/Personals", value: 434 },
  { label: "/Online Communities/Dating & Personals/Photo Rating Sites", value: 435 },
  { label: "/Online Communities/File Sharing & Hosting", value: 436 },
  { label: "/Online Communities/Online Goodies", value: 437 },
  { label: "/Online Communities/Online Goodies/Clip Art & Animated GIFs", value: 438 },
  { label: "/Online Communities/Online Goodies/Skins, Themes & Wallpapers", value: 439 },
  { label: "/Online Communities/Online Goodies/Social Network Apps & Add-Ons", value: 440 },
  { label: "/Online Communities/Photo & Video Sharing", value: 441 },
  { label: "/Online Communities/Photo & Video Sharing/Photo & Image Sharing", value: 442 },
  { label: "/Online Communities/Social Networks", value: 443 },
  { label: "/Online Communities/Virtual Worlds", value: 444 },
  { label: "/People & Society", value: 445 },
  { label: "/People & Society/Family & Relationships", value: 446 },
  { label: "/People & Society/Family & Relationships/Family", value: 447 },
  { label: "/People & Society/Family & Relationships/Marriage", value: 448 },
  { label: "/People & Society/Family & Relationships/Troubled Relationships", value: 449 },
  { label: "/People & Society/Kids & Teens", value: 450 },
  { label: "/People & Society/Kids & Teens/Children's Interests", value: 451 },
  { label: "/People & Society/Kids & Teens/Teen Interests", value: 452 },
  { label: "/People & Society/Religion & Belief", value: 453 },
  { label: "/People & Society/Seniors & Retirement", value: 454 },
  { label: "/People & Society/Social Issues & Advocacy", value: 455 },
  { label: "/People & Society/Social Issues & Advocacy/Charity & Philanthropy", value: 456 },
  { label: "/People & Society/Social Issues & Advocacy/Discrimination & Identity Relations", value: 457 },
  { label: "/People & Society/Social Issues & Advocacy/Green Living & Environmental Issues", value: 458 },
  { label: "/People & Society/Social Issues & Advocacy/Human Rights & Liberties", value: 459 },
  { label: "/People & Society/Social Issues & Advocacy/Poverty & Hunger", value: 460 },
  { label: "/People & Society/Social Issues & Advocacy/Work & Labor Issues", value: 461 },
  { label: "/People & Society/Social Sciences", value: 462 },
  { label: "/People & Society/Social Sciences/Economics", value: 463 },
  { label: "/People & Society/Social Sciences/Political Science", value: 464 },
  { label: "/People & Society/Social Sciences/Psychology", value: 465 },
  { label: "/People & Society/Subcultures & Niche Interests", value: 466 },
  { label: "/Pets & Animals", value: 467 },
  { label: "/Pets & Animals/Animal Products & Services/Pet Food & Supplies", value: 468 },
  { label: "/Pets & Animals/Animal Products & Services/Veterinarians", value: 469 },
  { label: "/Pets & Animals/Pets", value: 470 },
  { label: "/Pets & Animals/Pets/Birds", value: 471 },
  { label: "/Pets & Animals/Pets/Cats", value: 472 },
  { label: "/Pets & Animals/Pets/Dogs", value: 473 },
  { label: "/Pets & Animals/Pets/Exotic Pets", value: 474 },
  { label: "/Pets & Animals/Pets/Fish & Aquaria", value: 475 },
  { label: "/Pets & Animals/Pets/Horses", value: 476 },
  { label: "/Pets & Animals/Pets/Rabbits & Rodents", value: 477 },
  { label: "/Pets & Animals/Pets/Reptiles & Amphibians", value: 478 },
  { label: "/Pets & Animals/Wildlife", value: 479 },
  { label: "/Real Estate", value: 480 },
  { label: "/Real Estate/Real Estate Listings", value: 481 },
  { label: "/Real Estate/Real Estate Listings/Bank-Owned & Foreclosed Properties", value: 482 },
  { label: "/Real Estate/Real Estate Listings/Commercial Properties", value: 483 },
  { label: "/Real Estate/Real Estate Listings/Lots & Land", value: 484 },
  { label: "/Real Estate/Real Estate Listings/Residential Rentals", value: 485 },
  { label: "/Real Estate/Real Estate Listings/Residential Sales", value: 486 },
  { label: "/Real Estate/Real Estate Listings/Timeshares & Vacation Properties", value: 487 },
  { label: "/Real Estate/Real Estate Services", value: 488 },
  { label: "/Reference", value: 489 },
  { label: "/Reference/Directories & Listings", value: 490 },
  { label: "/Reference/Directories & Listings/Business & Personal Listings", value: 491 },
  { label: "/Reference/General Reference", value: 492 },
  { label: "/Reference/General Reference/Biographies & Quotations", value: 493 },
  { label: "/Reference/General Reference/Calculators & Reference Tools", value: 494 },
  { label: "/Reference/General Reference/Dictionaries & Encyclopedias", value: 495 },
  { label: "/Reference/General Reference/Forms Guides & Templates", value: 496 },
  { label: "/Reference/General Reference/Public Records", value: 497 },
  { label: "/Reference/General Reference/Time & Calendars", value: 498 },
  { label: "/Reference/Geographic Reference", value: 499 },
  { label: "/Reference/Geographic Reference/Maps", value: 500 },
  { label: "/Reference/Humanities", value: 501 },
  { label: "/Reference/Humanities/History", value: 502 },
  { label: "/Reference/Humanities/Myth & Folklore", value: 503 },
  { label: "/Reference/Humanities/Philosophy", value: 504 },
  { label: "/Reference/Language Resources", value: 505 },
  { label: "/Reference/Language Resources/Foreign Language Resources", value: 506 },
  { label: "/Reference/Libraries & Museums", value: 507 },
  { label: "/Reference/Libraries & Museums/Museums", value: 508 },
  { label: "/Science", value: 509 },
  { label: "/Science/Astronomy", value: 510 },
  { label: "/Science/Biological Sciences", value: 511 },
  { label: "/Science/Biological Sciences/Neuroscience", value: 512 },
  { label: "/Science/Chemistry", value: 513 },
  { label: "/Science/Computer Science", value: 514 },
  { label: "/Science/Earth Sciences", value: 515 },
  { label: "/Science/Earth Sciences/Atmospheric Science", value: 516 },
  { label: "/Science/Earth Sciences/Geology", value: 517 },
  { label: "/Science/Ecology & Environment", value: 518 },
  { label: "/Science/Ecology & Environment/Climate Change & Global Warming", value: 519 },
  { label: "/Science/Engineering & Technology", value: 520 },
  { label: "/Science/Engineering & Technology/Robotics", value: 521 },
  { label: "/Science/Mathematics", value: 522 },
  { label: "/Science/Mathematics/Statistics", value: 523 },
  { label: "/Science/Physics", value: 524 },
  { label: "/Science/Scientific Institutions", value: 525 },
  { label: "/Sensitive Subjects", value: 526 },
  { label: "/Shopping", value: 527 },
  { label: "/Shopping/Antiques & Collectibles", value: 528 },
  { label: "/Shopping/Apparel", value: 529 },
  { label: "/Shopping/Apparel/Athletic Apparel", value: 530 },
  { label: "/Shopping/Apparel/Casual Apparel", value: 531 },
  { label: "/Shopping/Apparel/Children's Clothing", value: 532 },
  { label: "/Shopping/Apparel/Clothing Accessories", value: 533 },
  { label: "/Shopping/Apparel/Costumes", value: 534 },
  { label: "/Shopping/Apparel/Eyewear", value: 535 },
  { label: "/Shopping/Apparel/Footwear", value: 536 },
  { label: "/Shopping/Apparel/Formal Wear", value: 537 },
  { label: "/Shopping/Apparel/Headwear", value: 538 },
  { label: "/Shopping/Apparel/Men's Clothing", value: 539 },
  { label: "/Shopping/Apparel/Swimwear", value: 540 },
  { label: "/Shopping/Apparel/Undergarments", value: 541 },
  { label: "/Shopping/Apparel/Women's Clothing", value: 542 },
  { label: "/Shopping/Auctions", value: 543 },
  { label: "/Shopping/Classifieds", value: 544 },
  { label: "/Shopping/Consumer Resources", value: 545 },
  { label: "/Shopping/Consumer Resources/Consumer Advocacy & Protection", value: 546 },
  { label: "/Shopping/Consumer Resources/Coupons & Discount Offers", value: 547 },
  { label: "/Shopping/Consumer Resources/Product Reviews & Price Comparisons", value: 548 },
  { label: "/Shopping/Entertainment Media", value: 549 },
  { label: "/Shopping/Entertainment Media/Entertainment Media Rentals", value: 550 },
  { label: "/Shopping/Gifts & Special Event Items", value: 551 },
  { label: "/Shopping/Gifts & Special Event Items/Cards & Greetings", value: 552 },
  { label: "/Shopping/Gifts & Special Event Items/Flowers", value: 553 },
  { label: "/Shopping/Gifts & Special Event Items/Gifts", value: 554 },
  { label: "/Shopping/Luxury Goods", value: 555 },
  { label: "/Shopping/Mass Merchants & Department Stores", value: 556 },
  { label: "/Shopping/Photo & Video Services", value: 557 },
  { label: "/Shopping/Tobacco Products", value: 558 },
  { label: "/Shopping/Toys", value: 559 },
  { label: "/Shopping/Toys/Building Toys", value: 560 },
  { label: "/Shopping/Toys/Die-cast & Toy Vehicles", value: 561 },
  { label: "/Shopping/Toys/Dolls & Accessories", value: 562 },
  { label: "/Shopping/Toys/Ride-On Toys & Wagons", value: 563 },
  { label: "/Shopping/Toys/Stuffed Toys", value: 564 },
  { label: "/Sports", value: 565 },
  { label: "/Sports/Animal Sports", value: 566 },
  { label: "/Sports/College Sports", value: 567 },
  { label: "/Sports/Combat Sports", value: 568 },
  { label: "/Sports/Combat Sports/Boxing", value: 569 },
  { label: "/Sports/Combat Sports/Martial Arts", value: 570 },
  { label: "/Sports/Combat Sports/Wrestling", value: 571 },
  { label: "/Sports/Extreme Sports", value: 572 },
  { label: "/Sports/Extreme Sports/Drag & Street Racing", value: 573 },
  { label: "/Sports/Fantasy Sports", value: 574 },
  { label: "/Sports/Individual Sports", value: 575 },
  { label: "/Sports/Individual Sports/Cycling", value: 576 },
  { label: "/Sports/Individual Sports/Golf", value: 577 },
  { label: "/Sports/Individual Sports/Gymnastics", value: 578 },
  { label: "/Sports/Individual Sports/Racquet Sports", value: 579 },
  { label: "/Sports/Individual Sports/Skate Sports", value: 580 },
  { label: "/Sports/Individual Sports/Track & Field", value: 581 },
  { label: "/Sports/International Sports Competitions", value: 582 },
  { label: "/Sports/International Sports Competitions/Olympics", value: 583 },
  { label: "/Sports/Motor Sports", value: 584 },
  { label: "/Sports/Sporting Goods", value: 585 },
  { label: "/Sports/Sporting Goods/Sports Memorabilia", value: 586 },
  { label: "/Sports/Sporting Goods/Winter Sports Equipment", value: 587 },
  { label: "/Sports/Sports Coaching & Training", value: 588 },
  { label: "/Sports/Team Sports", value: 589 },
  { label: "/Sports/Team Sports/American Football", value: 590 },
  { label: "/Sports/Team Sports/Australian Football", value: 591 },
  { label: "/Sports/Team Sports/Baseball", value: 592 },
  { label: "/Sports/Team Sports/Basketball", value: 593 },
  { label: "/Sports/Team Sports/Cheerleading", value: 594 },
  { label: "/Sports/Team Sports/Cricket", value: 595 },
  { label: "/Sports/Team Sports/Hockey", value: 596 },
  { label: "/Sports/Team Sports/Rugby", value: 597 },
  { label: "/Sports/Team Sports/Soccer", value: 598 },
  { label: "/Sports/Team Sports/Volleyball", value: 599 },
  { label: "/Sports/Water Sports", value: 600 },
  { label: "/Sports/Water Sports/Surfing", value: 601 },
  { label: "/Sports/Water Sports/Swimming", value: 602 },
  { label: "/Sports/Winter Sports", value: 603 },
  { label: "/Sports/Winter Sports/Ice Skating", value: 604 },
  { label: "/Sports/Winter Sports/Skiing & Snowboarding", value: 605 },
  { label: "/Travel", value: 606 },
  { label: "/Travel/Air Travel", value: 607 },
  { label: "/Travel/Air Travel/Airport Parking & Transportation", value: 608 },
  { label: "/Travel/Bus & Rail", value: 609 },
  { label: "/Travel/Car Rental & Taxi Services", value: 610 },
  { label: "/Travel/Cruises & Charters", value: 611 },
  { label: "/Travel/Hotels & Accommodations", value: 612 },
  { label: "/Travel/Hotels & Accommodations/Vacation Rentals & Short-Term Stays", value: 613 },
  { label: "/Travel/Specialty Travel", value: 614 },
  { label: "/Travel/Tourist Destinations", value: 615 },
  { label: "/Travel/Tourist Destinations/Beaches & Islands", value: 616 },
  { label: "/Travel/Tourist Destinations/Mountain & Ski Resorts", value: 617 },
  { label: "/Travel/Tourist Destinations/Regional Parks & Gardens", value: 618 },
  { label: "/Travel/Tourist Destinations/Theme Parks", value: 619 },
  { label: "/Travel/Tourist Destinations/Zoos-Aquariums-Preserves", value: 620 },

];
